{{- $servicePorts := list "0000" }}
{{- $root := . }}
{{- $values := $root.Values }}
{{- $deploymentsData := $values.deployments }}
{{ if $deploymentsData }}
{{- range $deploymentsData }}
{{ $currentDeployment := . }}
{{- range $currentDeployment.containers }}
{{ if .internalServicePort }}
{{ $servicePorts = append $servicePorts .internalServicePort }}
{{- end }}
{{- end }}
{{- if gt (len $servicePorts) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $currentDeployment.name }}
  namespace: {{ $values.namespace }}
spec:
  type: NodePort
  ports:
    {{- range $currentDeployment.containers }}
    {{- if .internalServicePort }}
    - port: {{ .internalServicePort }}
      protocol: TCP
      targetPort: {{ .containerPort }}
      {{ if .externalNodePort -}}
      nodePort: {{ .externalNodePort }}
      {{- end }}
      {{ if .servicePortName -}}
      name: {{ .servicePortName }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ $currentDeployment.name }}
{{ end }}
---
{{ end }}
{{ end }}
