# This file is usually git-ignored. Its just here for reference.
infraSettings:
  MONOLITH_MASTER_DATABASE_HOST: MC4wLjAuMA==
  MAZERUNNERS_DATABASE_HOST: MC4wLjAuMA==
  MAZERUNNERS_DATABASE_PORT: MzMwNg==
  SERVICE_A: ZGV2LmV4YW1wbGUuY29tL3NlcnZpY2VfYQ==
