name: build-image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "/*.sh"
      - ".gitignore"
      - "charts"
      - "*.md"

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        continue-on-error: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
        continue-on-error: false
      - name: Login to DockerHub
        continue-on-error: false
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set Version
        continue-on-error: false
        run: |
          echo VERSION=`grep -E "MAJOR|MINOR|PATCH" version.go | cut -d '"' -f 2 | xargs echo -n | tr -s " " "."` >> $GITHUB_ENV
      - name: Build and push
        continue-on-error: false
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nanda/hello-universe:v${{ env.VERSION }}
